name: Build and Release (x64)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Install NSIS
        run: choco install nsis

      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure build for amd64
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64
      
      - shell: cmd
        run: build.bat

      - name: Build Installer
        run: |
          makensis installer\slate.nsi
      
      - name: Verify artifact
        shell: cmd
        run: |
          if not exist build\slate.exe exit 1
          if not exist build\SetupSlate.exe exit 1

      - name: Rename artifact
        run: |
          copy build\slate.exe build\slate-${{ github.ref_name }}.exe
          copy build\SetupSlate.exe build\SetupSlate-${{ github.ref_name }}.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build/slate-${{ github.ref_name }}.exe
            build/SetupSlate-${{ github.ref_name }}.exe
